from __future__ import annotations

"""
Tests for the SUMO adapter using the toy_2x2_grid scenario.
"""

from pathlib import Path

from adapters.sumo.sumo_adapter import prepare_sumo_inputs


REPO_ROOT = Path(__file__).resolve().parents[1]
TOY_SCENARIO = REPO_ROOT / "scenarios" / "toy_2x2_grid"


def test_prepare_sumo_inputs_creates_expected_files(tmp_path) -> None:
    """
    Running prepare_sumo_inputs on the toy scenario should:

      - return a ScenarioSummary with the expected counts
      - create net.net.xml, routes.rou.xml, and toy.sumocfg
      - embed the correct scenario_id in the generated files
    """
    assert TOY_SCENARIO.is_dir(), f"Scenario directory not found: {TOY_SCENARIO}"

    out_dir = tmp_path / "sumo_out"
    summary = prepare_sumo_inputs(TOY_SCENARIO, out_dir)

    # Basic summary checks for the toy scenario
    assert summary.scenario_id == "toy_2x2_grid"
    assert summary.node_count == 4
    assert summary.link_count == 8
    assert summary.trip_count == 6
    assert summary.start_time_s == 0
    assert summary.end_time_s == 3600

    # Files must exist
    net_path = out_dir / "net.net.xml"
    routes_path = out_dir / "routes.rou.xml"
    cfg_path = out_dir / "toy.sumocfg"

    assert net_path.is_file(), f"Expected SUMO net file not found: {net_path}"
    assert routes_path.is_file(), f"Expected SUMO routes file not found: {routes_path}"
    assert cfg_path.is_file(), f"Expected SUMO config file not found: {cfg_path}"

    # Light content checks
    net_text = net_path.read_text(encoding="utf-8")
    routes_text = routes_path.read_text(encoding="utf-8")
    cfg_text = cfg_path.read_text(encoding="utf-8")

    # Scenario ID should appear in routes (net.xml is generated by netconvert)
    assert "toy_2x2_grid" in routes_text

    # At least one vehicle and route entry should be present
    assert "<vehicle" in routes_text
    assert "<route" in routes_text

    # Config should reference the expected net and routes files
    assert 'net-file value="net.net.xml"' in cfg_text
    assert 'route-files value="routes.rou.xml"' in cfg_text