"""
Build a complete canonical scenario bundle.

Orchestrates network, demand, and signals generation, then assembles
config.xml and manifest.xml with proper hashes.

Usage:
    python -m pipeline.scenariobuilder.build_bundle \
        --city sioux_falls \
        --trips 50000 \
        --output scenarios/sioux_falls_tier50k

Or with custom bounding box:
    python -m pipeline.scenariobuilder.build_bundle \
        --bbox "43.59,43.50,-96.68,-96.78" \
        --scenario-id "custom_city" \
        --trips 50000 \
        --output scenarios/custom_tier50k
"""

import hashlib
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional
import logging

from lxml import etree

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def compute_sha256(filepath: Path) -> str:
    """Compute SHA256 hash of a file."""
    sha256 = hashlib.sha256()
    with open(filepath, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()


def build_config_xml(
    scenario_id: str,
    city: str,
    tier: str,
    horizon_start_s: int,
    horizon_end_s: int,
    time_step_s: float,
    random_seed: int,
    crs: str,
    schema_version: str = "0.1.0"
) -> etree.Element:
    """
    Build canonical config.xml.
    
    Returns:
        lxml Element tree root
    """
    root = etree.Element("config")
    
    # Metadata element (required per schema)
    metadata = etree.SubElement(root, "metadata")
    metadata.set("scenario_id", scenario_id)
    metadata.set("created_by", "SimForge Pipeline")
    metadata.set("created_at", datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"))
    
    desc = etree.SubElement(metadata, "description")
    desc.text = f"Canonical scenario for {city}, tier {tier}"
    
    # Time settings
    time = etree.SubElement(root, "time")
    time.set("start_time_s", str(horizon_start_s))
    time.set("end_time_s", str(horizon_end_s))
    time.set("time_step_s", str(int(time_step_s)))
    
    # Random seed
    random_elem = etree.SubElement(root, "random")
    random_elem.set("seed", str(random_seed))
    random_elem.set("engine_seed_mode", "fixed")
    
    # Units (required per schema)
    units = etree.SubElement(root, "units")
    units.set("length", "meters")
    units.set("speed", "m/s")
    units.set("time", "seconds")
    
    # Optional simulation settings
    simulation = etree.SubElement(root, "simulation")
    simulation.set("warmup_time_s", "0")
    simulation.set("aggregation_interval_s", "300")
    
    return root


def build_manifest_xml(
    scenario_id: str,
    output_dir: Path,
    scenario_name: Optional[str] = None,
    description: str = "Generated by SimForge Pipeline"
) -> etree.Element:
    """
    Build manifest.xml with file hashes.
    
    Args:
        scenario_id: Scenario identifier
        output_dir: Directory containing canonical files
        scenario_name: Human-friendly scenario name
        description: Scenario description
    
    Returns:
        lxml Element tree root
    """
    root = etree.Element("manifest")
    
    # Scenario element (required per schema)
    scenario_elem = etree.SubElement(root, "scenario")
    scenario_elem.set("id", scenario_id)
    scenario_elem.set("name", scenario_name or scenario_id.replace("_", " ").title())
    
    desc_elem = etree.SubElement(scenario_elem, "description")
    desc_elem.text = description
    
    # File list with hashes
    files_elem = etree.SubElement(root, "canonical_files")
    
    # Canonical files with type attribute (per schema)
    canonical_files = [
        ("network.xml", "network", True),
        ("demand.csv", "demand", True),
        ("signals.xml", "signals", False),
        ("config.xml", "config", True)
    ]
    
    for filename, file_type, required in canonical_files:
        filepath = output_dir / filename
        if filepath.exists():
            file_elem = etree.SubElement(files_elem, "file")
            file_elem.set("type", file_type)
            file_elem.set("path", filename)
            file_elem.set("required", "true" if required else "false")
            file_elem.set("sha256", compute_sha256(filepath))
            file_elem.set("size_bytes", str(filepath.stat().st_size))
    
    # Optional metadata
    metadata = etree.SubElement(root, "metadata")
    metadata.set("generated_at", datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"))
    metadata.set("generator", "SimForge Pipeline v0.1.0")
    
    return root


def build_bundle(
    output_dir: Path,
    scenario_id: str,
    city: str,
    tier: str,
    num_trips: int,
    horizon_start_s: int = 0,
    horizon_end_s: int = 3600,
    time_step_s: float = 1.0,
    random_seed: int = 42,
    crs: str = "EPSG:4326",
    bbox: Optional[str] = None,
    city_key: Optional[str] = None,
    demand_strategy: str = "gravity",
    min_signal_degree: int = 4,
    max_signals: Optional[int] = None
) -> dict:
    """
    Build a complete canonical scenario bundle.
    
    This orchestrates:
    1. Network from OSM
    2. Synthetic demand
    3. Default signals
    4. Config and manifest
    
    Args:
        output_dir: Directory to create bundle in
        scenario_id: Unique scenario identifier
        city: City name for metadata
        tier: Demand tier label (e.g., "50k", "500k")
        num_trips: Number of trips to generate
        horizon_start_s: Simulation start time
        horizon_end_s: Simulation end time
        time_step_s: Simulation time step
        random_seed: Random seed for reproducibility
        crs: Coordinate reference system
        bbox: Optional bounding box string "north,south,east,west"
        city_key: Optional predefined city key
        demand_strategy: Demand generation strategy
        min_signal_degree: Minimum node degree for signals
        max_signals: Optional max signals limit
    
    Returns:
        Summary dict with all component statistics
    """
    from pipeline.network.build_network_from_osm import (
        build_network_from_osm, BoundingBox, get_city_bbox
    )
    from pipeline.demand.generate_synthetic_demand import generate_synthetic_demand
    from pipeline.signals.build_signals_default import build_signals_default
    
    # Create output directory
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    logger.info(f"Building bundle: {scenario_id}")
    logger.info(f"Output directory: {output_dir}")
    
    # Step 1: Build network from OSM
    logger.info("Step 1: Building network from OSM...")
    if bbox:
        network_bbox = BoundingBox.from_string(bbox)
    elif city_key:
        network_bbox = get_city_bbox(city_key)
    else:
        raise ValueError("Either --bbox or --city is required")
    
    network_path = output_dir / "network.xml"
    network_result = build_network_from_osm(
        bbox=network_bbox,
        output_path=network_path,
        crs=crs
    )
    logger.info(f"  Network: {network_result['node_count']} nodes, {network_result['link_count']} links")
    
    # Step 2: Generate synthetic demand
    logger.info("Step 2: Generating synthetic demand...")
    demand_path = output_dir / "demand.csv"
    demand_result = generate_synthetic_demand(
        network_path=network_path,
        output_path=demand_path,
        num_trips=num_trips,
        strategy=demand_strategy,
        seed=random_seed,
        horizon_start=horizon_start_s,
        horizon_end=horizon_end_s
    )
    logger.info(f"  Demand: {demand_result['trip_count']} trips")
    
    # Step 3: Build default signals
    logger.info("Step 3: Building default signals...")
    signals_path = output_dir / "signals.xml"
    signals_result = build_signals_default(
        network_path=network_path,
        output_path=signals_path,
        min_degree=min_signal_degree,
        max_signals=max_signals
    )
    logger.info(f"  Signals: {signals_result['signal_count']} controllers")
    
    # Step 4: Build config.xml
    logger.info("Step 4: Building config.xml...")
    config_root = build_config_xml(
        scenario_id=scenario_id,
        city=city,
        tier=tier,
        horizon_start_s=horizon_start_s,
        horizon_end_s=horizon_end_s,
        time_step_s=time_step_s,
        random_seed=random_seed,
        crs=crs
    )
    config_path = output_dir / "config.xml"
    config_tree = etree.ElementTree(config_root)
    config_tree.write(str(config_path), pretty_print=True, xml_declaration=True, encoding="UTF-8")
    
    # Step 5: Build manifest.xml
    logger.info("Step 5: Building manifest.xml...")
    manifest_root = build_manifest_xml(
        scenario_id=scenario_id,
        output_dir=output_dir
    )
    manifest_path = output_dir / "manifest.xml"
    manifest_tree = etree.ElementTree(manifest_root)
    manifest_tree.write(str(manifest_path), pretty_print=True, xml_declaration=True, encoding="UTF-8")
    
    logger.info("Bundle complete!")
    
    return {
        "scenario_id": scenario_id,
        "output_dir": str(output_dir),
        "network": network_result,
        "demand": demand_result,
        "signals": signals_result,
        "files": [
            "network.xml",
            "demand.csv",
            "signals.xml",
            "config.xml",
            "manifest.xml"
        ]
    }


def main():
    """CLI entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Build complete canonical scenario bundle"
    )
    
    # Location specification
    location_group = parser.add_mutually_exclusive_group(required=True)
    location_group.add_argument(
        "--city", type=str,
        choices=["sioux_falls", "anaheim", "austin_downtown", "manhattan_midtown", "sf_downtown"],
        help="Predefined city key"
    )
    location_group.add_argument(
        "--bbox", type=str,
        help="Custom bounding box as 'north,south,east,west'"
    )
    
    # Output
    parser.add_argument(
        "--output", "-o", type=str, required=True,
        help="Output directory for bundle"
    )
    
    # Scenario metadata
    parser.add_argument(
        "--scenario-id", type=str,
        help="Scenario identifier (default: derived from city/tier)"
    )
    parser.add_argument(
        "--city-name", type=str,
        help="City name for metadata (default: derived from --city)"
    )
    
    # Demand settings
    parser.add_argument(
        "--trips", "-t", type=int, default=50000,
        help="Number of trips (default: 50000)"
    )
    parser.add_argument(
        "--demand-strategy", type=str, default="gravity",
        choices=["uniform", "gravity", "peak_hour"],
        help="Demand generation strategy (default: gravity)"
    )
    
    # Time settings
    parser.add_argument(
        "--horizon-start", type=int, default=0,
        help="Simulation start time in seconds (default: 0)"
    )
    parser.add_argument(
        "--horizon-end", type=int, default=3600,
        help="Simulation end time in seconds (default: 3600)"
    )
    parser.add_argument(
        "--seed", type=int, default=42,
        help="Random seed (default: 42)"
    )
    
    # Signal settings
    parser.add_argument(
        "--min-signal-degree", type=int, default=4,
        help="Minimum node degree for signalization (default: 4)"
    )
    parser.add_argument(
        "--max-signals", type=int, default=None,
        help="Maximum number of signals (default: unlimited)"
    )
    
    args = parser.parse_args()
    
    # Derive defaults
    city_key = args.city
    if args.scenario_id:
        scenario_id = args.scenario_id
    elif city_key:
        tier_label = f"{args.trips // 1000}k" if args.trips >= 1000 else str(args.trips)
        scenario_id = f"{city_key}_tier{tier_label}"
    else:
        scenario_id = "custom_scenario"
    
    city_name = args.city_name or (city_key.replace("_", " ").title() if city_key else "Custom City")
    tier_label = f"{args.trips // 1000}k" if args.trips >= 1000 else str(args.trips)
    
    result = build_bundle(
        output_dir=Path(args.output),
        scenario_id=scenario_id,
        city=city_name,
        tier=tier_label,
        num_trips=args.trips,
        horizon_start_s=args.horizon_start,
        horizon_end_s=args.horizon_end,
        random_seed=args.seed,
        bbox=args.bbox,
        city_key=city_key,
        demand_strategy=args.demand_strategy,
        min_signal_degree=args.min_signal_degree,
        max_signals=args.max_signals
    )
    
    print(f"\n{'='*60}")
    print(f"Bundle built successfully: {result['scenario_id']}")
    print(f"{'='*60}")
    print(f"  Output: {result['output_dir']}")
    print(f"  Network: {result['network']['node_count']} nodes, {result['network']['link_count']} links")
    print(f"  Demand: {result['demand']['trip_count']} trips")
    print(f"  Signals: {result['signals']['signal_count']} controllers")
    print(f"\nFiles created:")
    for f in result['files']:
        print(f"  - {f}")
    print(f"\nValidate with:")
    print(f"  python -m pipeline.validation.validate_bundle {result['output_dir']}")


if __name__ == "__main__":
    main()
